title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: |
  <p align="center"> ALHAMDULILLAH </p>
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
Ñol Ivan Juan de Dios Rojas es un profesional egresado de la Universidad Nacional de San Cristóbal de Huamanga, especializado en automatización y programación aplicada a la ingeniería civil. Se interesa en la fotogrametría y el uso de tecnologías para crear modelos 3D útiles en topografía, monitoreo de infraestructuras y modelos digitales del terreno (DTM), siempre buscando hacer los proyectos más eficientes.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax

