title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: |
  <p align="center"> ALHAMDULILLAH </p>
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
Ñol Ivan Juan de Dios Rojas es un profesional egresado de la Universidad Nacional de San Cristóbal de Huamanga. Se especializa en la automatización y programación aplicada a la ingeniería civil, con el objetivo de mejorar la gestión y desarrollo de proyectos. Tiene un gran interés en la fotogrametría, utilizando tecnologías de captura y procesamiento de imágenes para crear modelos 3D precisos, aplicados en topografía, monitoreo de infraestructuras y la creación de modelos digitales del terreno (DTM). Siempre busca nuevas formas de aplicar la tecnología para hacer los proyectos más eficientes y lograr mejores resultados.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax

