title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: |
  <p align="center"> ALHAMDULILLAH </p>
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
  Profesional egresado de la Universidad Nacional de San Cristóbal de Huamanga, con una sólida formación en la automatización y programación aplicada a la ingeniería civil. Mi enfoque principal está en la interoperabilidad de programas y la implementación de soluciones tecnológicas avanzadas que optimicen procesos y potencien la eficiencia en proyectos de ingeniería. Mi pasión por la innovación me lleva a explorar constantemente nuevas tecnologías que mejoren la gestión y ejecución de proyectos, buscando siempre maximizar los resultados.
   Con un interés particular en la fotogrametría, me dedico a integrar técnicas avanzadas de captura y procesamiento de imágenes para obtener mediciones precisas y modelos 3D. Este enfoque es esencial para aplicaciones en topografía, monitoreo de infraestructuras y la creación de modelos digitales del terreno (DTM), brindando una visión más detallada y precisa de los proyectos de ingeniería.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax

