title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/FOTO.png

description: |
  <p align="center"> ALHAMDULILLAH </p>
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
  Profesional egresado de la carrera de Ingeniería Civil de la Universidad Nacional de San Cristobal de Huamanga. Apasionado por la automatización y la programación aplicada a la ingeniería civil, con un enfoque en la interoperabilidad de programas y la fotogrametría. Entusiasta de la implementación de soluciones tecnológicas avanzadas para optimizar procesos y potenciar la eficiencia en proyectos de ingeniería.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax

# Social Media Buttons Configuration
social_buttons:
  facebook: "https://www.facebook.com/nolivan.juandediosrojas/"
  instagram: "https://www.instagram.com/ivan_jdd_tjgo/"
  x: "https://x.com/ivanjuandedios1"
  github: "https://github.com/TJGO-JDD"
  linkedin: "https://www.linkedin.com/in/%C3%B1ol-ivan-juan-de-dios-rojas-600b36273/"
  youtube: "https://www.youtube.com/@nolivanjuandediosrojas7820"
  tiktok: "https://www.tiktok.com/@ivanjddhood"
  whatsapp: "https://wa.me/51917726087?text=Deseo%20informaci%C3%B3n%20sobre!%20...."
  spotify: "https://open.spotify.com/user/21crxkbqieguhc6ogdkcf4hey?si=nde5_d97ShukDvxHakioQQ"
