title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/FOTO.png

description: |
  <p align="center"> ALHAMDULILLAH </p>
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
  Profesional egresado de la carrera de Ingeniería Civil de la Universidad Nacional de San Cristobal de Huamanga. Apasionado por la automatización y la programación aplicada a la ingeniería civil, con un enfoque en la interoperabilidad de programas y la fotogrametría. Entusiasta de la implementación de soluciones tecnológicas avanzadas para optimizar procesos y potenciar la eficiencia en proyectos de ingeniería.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax

